/*
* generated by Xtext
*/
package br.ufes.inf.filesystem.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FsDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
