/*
 * generated by Xtext
 */
package br.ufes.inf.filesystem.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return br.ufes.inf.filesystem.ui.internal.FsDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return br.ufes.inf.filesystem.ui.internal.FsDslActivator.getInstance().getInjector("br.ufes.inf.filesystem.FsDsl");
	}
	
}
