/*
 * generated by Xtext
 */
package br.ufes.inf.filesystem;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */

public class FsDslRuntimeModule extends br.ufes.inf.filesystem.AbstractFsDslRuntimeModule {
	

}
