/*
 * generated by Xtext
 */
package br.ufes.inf.filesystem.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FsDslUiModule extends br.ufes.inf.filesystem.ui.AbstractFsDslUiModule {
	public FsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
