/*
* generated by Xtext
*/
package br.ufes.inf.filesystem.ui.contentassist;

import br.ufes.inf.filesystem.ui.contentassist.AbstractFsDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FsDslProposalProvider extends AbstractFsDslProposalProvider {

}
